restart:
   script:
    - "unset http_proxy"
    - "git remote add staging git@10.73.53.112:EV-Contributions/loopback-connector-nodes-for-Node-RED.git"
    - "git push staging master"
    - "cd .."
    - "git clone git@10.73.53.167:ev/loopback-connector-nodes-for-Node-RED.wiki.git"
    - "git remote add staging git@10.73.53.112:EV-Contributions/loopback-connector-nodes-for-Node-RED.wiki.git"
    - "git push staging master"